const palabrasReservadas = [
    {
        id: '1',
        item: 'if',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '2',
        item: 'else',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '3',
        item: 'forEach',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '4',
        item: 'break',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '5',
        item: 'switch',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '6',
        item: 'case',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '7',
        item: ':',
        value: 'Delimitador 2 puntos',
        type: 'delimitador',
    },
    {
        id: '8',
        item: 'while',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '9',
        item: 'const',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '10',
        item: 'let',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '11',
        item: 'var',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '12',
        item: 'function',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '13',
        item: '||',
        value: 'Operador Logico OR (O)',
        type: 'logico',
    },
    {
        id: '14',
        item: '&&',
        value: 'Operador Logico AND (Y)',
        type: 'logico',
    },
    {
        id: '15',
        item: '**',
        value: 'Operador aritmético potencia',
        type: 'aritmetico',
    },
    {
        id: '16',
        item: '===',
        value: 'Operador relacional igual que',
        type: 'relacional',
    },
    {
        id: '17',
        item: '!==',
        value: 'Operador relacional diferente ',
        type: 'relacional',
    },
    {
        id: '18',
        item: '==',
        value: 'Operador relacional igual',
        type: 'relacional',
    },
    {
        id: '19',
        item: '>=',
        value: 'Operador relacional mayor o igual',
        type: 'relacional',
    },
    {
        id: '20',
        item: '>',
        value: 'Operador relacional mayor',
        type: 'relacional',
    },
    {
        id: '21',
        item: '<=',
        value: 'Operador relacional menor o igual',
        type: 'relacional',
    },
    {
        id: '22',
        item: '<',
        value: 'Operador relacional menor',
        type: 'relacional',
    },
    {
        id: '23',
        item: '=',
        value: 'Operador relacional de asignacion',
        type: 'relacional',
    },
    {
        id: '24',
        item: '++',
        value: 'Operador aritmético aumentar y asignar',
        type: 'aritmetico',
    },
    {
        id: '25',
        item: '--',
        value: 'Operador aritmético restar y asignar',
        type: 'aritmetico',
    },
    {
        id: '26',
        item: '*=',
        value: 'Operador aritmético multiplicar y asignar',
        type: 'aritmetico',
    },
    {
        id: '27',
        item: '/=',
        value: 'Operador aritmético dividir y asignar',
        type: 'aritmetico',
    },
    {
        id: '28',
        item: '+',
        value: 'Operador aritmético suma',
        type: 'aritmetico',
    },
    {
        id: '29',
        item: '-',
        value: 'Operador aritmético resta',
        type: 'aritmetico',
    },
    {
        id: '30',
        item: '*',
        value: 'Operador aritmético multiplicación',
        type: 'aritmetico',
    },
    {
        id: '31',
        item: '//',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '32',
        item: '%',
        value: 'Operador aritmético residuo',
        type: 'aritmetico',
    },
    {
        id: '33',
        item: 'console.log',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '34',
        item: ';',
        value: 'Punto y coma',
        type: 'delimitador',
    },
    {
        id: '35',
        item: ',',
        value: 'Coma',
        type: 'delimitador',
    },
    {
        id: '36',
        item: '(',
        value: 'Delimitador parentesis',
        type: 'delimitador',
    },
    {
        id: '37',
        item: ')',
        value: 'Delimitador parentesis',
        type: 'delimitador',
    },
    {
        id: '38',
        item: '{',
        value: 'Delimitador llave',
        type: 'delimitador',
    },
    {
        id: '39',
        item: '}',
        value: 'Delimitador llave',
        type: 'delimitador',
    },
    {
        id: '40',
        item: '[',
        value: 'Delimitador corchete',
        type: 'delimitador',
    },
    {
        id: '41',
        item: ']',
        value: 'Delimitador corchete',
        type: 'delimitador',
    },
    {
        id: '42',
        item: '.',
        value: 'Punto',
        type: 'delimitador',
    },
    {
        id: '43',
        item: 'for',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '44',
        item: '$',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '45',
        item: 'filter',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '46',
        item: 'replace',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '47',
        item: 'chartAt',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '48',
        item: 'repeat',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '49',
        item: 'split',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '50',
        item: 'join',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '51',
        item: 'toLowerCase',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '52',
        item: 'toUpperCase',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '53',
        item: 'setTimeout',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '54',
        item: '=>',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '55',
        item: 'then',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '56',
        item: 'catch',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '57',
        item: 'slice',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '58',
        item: 'indexOf',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '59',
        item: 'sort',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '60',
        item: 'map',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '61',
        item: 'then',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '62',
        item: 'cath',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '63',
        item: 'reject',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '64',
        item: 'resolve',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '65',
        item: 'promise',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '66',
        item: 'return',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '67',
        item: 'null',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '68',
        item: 'undenifed',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '69',
        item: 'value',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '70',
        item: 'length',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '71',
        item: 'true',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '72',
        item: 'false',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '73',
        item: '/',
        value: 'Operador aritmético división',
        type: 'aritmetico',
    },
    {
        id: '74',
        item: 'default',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '75',
        item: '!',
        value: 'Operador logico NOT',
        type: 'palabraReservada',
    },
    {
        id: '76',
        item: 'import',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
    {
        id: '77',
        item: 'from',
        value: 'Palabra reservada',
        type: 'palabraReservada',
    },
];

export default palabrasReservadas;
